config/routes.rb
Rails.application.routes.draw do
  resources :voices
  root "voices#index"
end

app/models/voice.rb
class Voice < ActiveRecord::Base
	validates_presence_of :title, :opinion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController

	before_action :find_voice, only: [:show, :edit, :update, :destroy]

	def index
		@voices = Voice.all
	end

	def new
		@voice = Voice.new
	end

	def create
		@voice = Voice.new(voices_params)
		if @voice.save
			redirect_to @voice
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @voice.update(voices_params)
			redirect_to @voice
		else
			render "edit"
		end
	end

	def destroy
		@voice.destroy
		redirect_to root_path
	end

	private

	def voices_params
		params.require(:voice).permit(:title, :opinion)
	end

	def find_voice
		@voice = Voice.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voicewall</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voices/edit.html.haml
= simple_form_for @voice do |f|
	= f.input :title
	= f.input :opinion
	= f.submit

app/views/voices/index.html.haml
- @voices.each do |voice|
	%h2
		=link_to voice.title, voice
	%p= voice.opinion


= link_to "New Voice", new_voice_path

app/views/voices/new.html.haml
= simple_form_for @voice do |f|
	= f.input :title
	= f.input :opinion
	= f.submit

app/views/voices/show.html.haml
%h2= @voice.title
%p= @voice.opinion

= link_to "Edit", edit_voice_path(@voice)
= link_to "Destroy", voice_path(@voice), method: :delete, data: {confirm: "Are you sure?"}